version: "3.8"

services:
  mongo_db:
    image: mongo:latest
    container_name: "mongo"
    ports:
      - "27017:27017"
    networks:
      - order-service-net

  exam-restaurant-service:
    image: exam-restaurant-service:latest
    container_name: "exam-restaurant-service"
    ports:
      - "9090:8080"
    environment:
        SPRING_RABBITMQ_HOST: rabbitmq
        SPRING_RABBITMQ_PORT: 5672
    networks:
      - order-service-net

networks:
  order-service-net:
    external:
     name: order-service-net
