version: "3.8"

services:
  mongo_db:
    image: mongo:latest
    container_name: "mongo"
    ports:
      - "27017:27017"
    networks:
      - exam-mtgo

  exam-restaurant-service:
    container_name: restaurant-service
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
        SPRING_PROFILES_ACTIVE: docker
    networks:
      - exam-mtgo

networks:
  exam-mtgo:
