version: "3.8"

services:
  mongo_db:
    image: mongo:latest
    container_name: "mongo"
    ports:
      - 27017:27017

  exam-restaurant-service:
    image: exam-restaurant-service:latest
    container_name: "exam-restaurant-service"
    ports:
      - 9090:8080
    links:
      - mongo_db
